[graph]
all-features = true
no-default-features = false

[advisories]
ignore = []
unmaintained = "all"
yanked = "deny"

[licenses]
allow = [
    "GPL-3.0-or-later",
    "MIT",
    "Apache-2.0",
    "ISC",
    "Unicode-3.0",
    "MPL-2.0",
    "BSD-3-Clause",
]

exceptions = [
    { allow = ["CDLA-Permissive-2.0"], crate = "webpki-root-certs" }
]

confidence-threshold = 0.8

[[licenses.clarify]]
crate = "ring"
expression = "MIT AND ISC AND OpenSSL"

license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[bans]
multiple-versions = "deny"
wildcards = "deny"
workspace-default-features = "allow"
external-default-features = "allow"

skip = [
    "getrandom@0.2.17",
    "getrandom@0.4.3",
    "base64@0.22.1",
]

skip-tree = [
{ crate = "postcard" }
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"

allow-registry = [
    "https://github.com/rust-lang/crates.io-index",
]

allow-git = [
    "https://github.com/jamesmunns/postcard",
]
