name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Pipery Rust CI Pipeline
        uses: pipery-dev/rust-ci@v1
        with:
          rust_toolchain: stable
          features: "--all-features"
          skip_sast: false
          skip_sca: false
          skip_lint: false
          skip_build: false
          skip_test: false
