name: Release

on:
  push:
    tags:
      - 'v*' 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Release Linux Binary
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: x86_64-unknown-linux-gnu
          ARCHIVE_TYPES: tar.gz
          MINIFY: "true"         
          UPLOAD_MODE: release   
